//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Booksclub
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Спикер.
    /// </summary>
    // *** Start programmer edit section *** (Spiker CustomAttributes)

    // *** End programmer edit section *** (Spiker CustomAttributes)
    [AutoAltered()]
    [Caption("Спикер")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("SpikerE", new string[] {
            "Familiya as \'Фамилия\'",
            "Imya as \'Имя\'",
            "Otchestvo as \'Отчество\'"})]
    [View("SpikerL", new string[] {
            "Familiya as \'Фамилия\'",
            "Imya as \'Имя\'",
            "Otchestvo as \'Отчество\'"})]
    public class Spiker : ICSSoft.STORMNET.DataObject
    {
        
        private string fFamiliya;
        
        private string fImya;
        
        private string fOtchestvo;
        
        // *** Start programmer edit section *** (Spiker CustomMembers)

        // *** End programmer edit section *** (Spiker CustomMembers)

        
        /// <summary>
        /// Familiya.
        /// </summary>
        // *** Start programmer edit section *** (Spiker.Familiya CustomAttributes)

        // *** End programmer edit section *** (Spiker.Familiya CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Familiya
        {
            get
            {
                // *** Start programmer edit section *** (Spiker.Familiya Get start)

                // *** End programmer edit section *** (Spiker.Familiya Get start)
                string result = this.fFamiliya;
                // *** Start programmer edit section *** (Spiker.Familiya Get end)

                // *** End programmer edit section *** (Spiker.Familiya Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Spiker.Familiya Set start)

                // *** End programmer edit section *** (Spiker.Familiya Set start)
                this.fFamiliya = value;
                // *** Start programmer edit section *** (Spiker.Familiya Set end)

                // *** End programmer edit section *** (Spiker.Familiya Set end)
            }
        }
        
        /// <summary>
        /// Imya.
        /// </summary>
        // *** Start programmer edit section *** (Spiker.Imya CustomAttributes)

        // *** End programmer edit section *** (Spiker.Imya CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Imya
        {
            get
            {
                // *** Start programmer edit section *** (Spiker.Imya Get start)

                // *** End programmer edit section *** (Spiker.Imya Get start)
                string result = this.fImya;
                // *** Start programmer edit section *** (Spiker.Imya Get end)

                // *** End programmer edit section *** (Spiker.Imya Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Spiker.Imya Set start)

                // *** End programmer edit section *** (Spiker.Imya Set start)
                this.fImya = value;
                // *** Start programmer edit section *** (Spiker.Imya Set end)

                // *** End programmer edit section *** (Spiker.Imya Set end)
            }
        }
        
        /// <summary>
        /// Otchestvo.
        /// </summary>
        // *** Start programmer edit section *** (Spiker.Otchestvo CustomAttributes)

        // *** End programmer edit section *** (Spiker.Otchestvo CustomAttributes)
        [StrLen(255)]
        public virtual string Otchestvo
        {
            get
            {
                // *** Start programmer edit section *** (Spiker.Otchestvo Get start)

                // *** End programmer edit section *** (Spiker.Otchestvo Get start)
                string result = this.fOtchestvo;
                // *** Start programmer edit section *** (Spiker.Otchestvo Get end)

                // *** End programmer edit section *** (Spiker.Otchestvo Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Spiker.Otchestvo Set start)

                // *** End programmer edit section *** (Spiker.Otchestvo Set start)
                this.fOtchestvo = value;
                // *** Start programmer edit section *** (Spiker.Otchestvo Set end)

                // *** End programmer edit section *** (Spiker.Otchestvo Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "SpikerE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SpikerE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SpikerE", typeof(IIS.Booksclub.Spiker));
                }
            }
            
            /// <summary>
            /// "SpikerL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SpikerL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SpikerL", typeof(IIS.Booksclub.Spiker));
                }
            }
        }
    }
}
