//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Booksclub
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Встреча клуба.
    /// </summary>
    // *** Start programmer edit section *** (VstrechaKluba CustomAttributes)

    // *** End programmer edit section *** (VstrechaKluba CustomAttributes)
    [AutoAltered()]
    [Caption("Встреча клуба")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("VstrechaKlubaE", new string[] {
            "DataVstrechi as \'Дата встречи\'"})]
    [AssociatedDetailViewAttribute("VstrechaKlubaE", "Doklad", "DokladE", true, "", "Доклад", true, new string[] {
            ""})]
    [View("VstrechaKlubaL", new string[] {
            "DataVstrechi as \'Дата встречи\'"})]
    public class VstrechaKluba : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fDataVstrechi;
        
        private IIS.Booksclub.DetailArrayOfDoklad fDoklad;
        
        // *** Start programmer edit section *** (VstrechaKluba CustomMembers)

        // *** End programmer edit section *** (VstrechaKluba CustomMembers)

        
        /// <summary>
        /// DataVstrechi.
        /// </summary>
        // *** Start programmer edit section *** (VstrechaKluba.DataVstrechi CustomAttributes)

        // *** End programmer edit section *** (VstrechaKluba.DataVstrechi CustomAttributes)
        [NotNull()]
        public virtual System.DateTime DataVstrechi
        {
            get
            {
                // *** Start programmer edit section *** (VstrechaKluba.DataVstrechi Get start)

                // *** End programmer edit section *** (VstrechaKluba.DataVstrechi Get start)
                System.DateTime result = this.fDataVstrechi;
                // *** Start programmer edit section *** (VstrechaKluba.DataVstrechi Get end)

                // *** End programmer edit section *** (VstrechaKluba.DataVstrechi Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (VstrechaKluba.DataVstrechi Set start)

                // *** End programmer edit section *** (VstrechaKluba.DataVstrechi Set start)
                this.fDataVstrechi = value;
                // *** Start programmer edit section *** (VstrechaKluba.DataVstrechi Set end)

                // *** End programmer edit section *** (VstrechaKluba.DataVstrechi Set end)
            }
        }
        
        /// <summary>
        /// Встреча клуба.
        /// </summary>
        // *** Start programmer edit section *** (VstrechaKluba.Doklad CustomAttributes)

        // *** End programmer edit section *** (VstrechaKluba.Doklad CustomAttributes)
        public virtual IIS.Booksclub.DetailArrayOfDoklad Doklad
        {
            get
            {
                // *** Start programmer edit section *** (VstrechaKluba.Doklad Get start)

                // *** End programmer edit section *** (VstrechaKluba.Doklad Get start)
                if ((this.fDoklad == null))
                {
                    this.fDoklad = new IIS.Booksclub.DetailArrayOfDoklad(this);
                }
                IIS.Booksclub.DetailArrayOfDoklad result = this.fDoklad;
                // *** Start programmer edit section *** (VstrechaKluba.Doklad Get end)

                // *** End programmer edit section *** (VstrechaKluba.Doklad Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (VstrechaKluba.Doklad Set start)

                // *** End programmer edit section *** (VstrechaKluba.Doklad Set start)
                this.fDoklad = value;
                // *** Start programmer edit section *** (VstrechaKluba.Doklad Set end)

                // *** End programmer edit section *** (VstrechaKluba.Doklad Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "VstrechaKlubaE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View VstrechaKlubaE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("VstrechaKlubaE", typeof(IIS.Booksclub.VstrechaKluba));
                }
            }
            
            /// <summary>
            /// "VstrechaKlubaL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View VstrechaKlubaL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("VstrechaKlubaL", typeof(IIS.Booksclub.VstrechaKluba));
                }
            }
        }
    }
}
