




CREATE TABLE Booksclub (
 primaryKey UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Doklad (
 primaryKey UUID NOT NULL,
 DataDoklada TIMESTAMP(3) NOT NULL,
 OcenkaKnigi INT NULL,
 URLPrezentacii VARCHAR(255) NULL,
 URLVideo VARCHAR(255) NULL,
 Recenziya VARCHAR(255) NULL,
 Spiker_m0 UUID NOT NULL,
 Kniga_m0 UUID NOT NULL,
 VstrechaKluba_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE VstrechaKluba (
 primaryKey UUID NOT NULL,
 DataVstrechi TIMESTAMP(3) NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Kniga (
 primaryKey UUID NOT NULL,
 Nazvanie VARCHAR(255) NULL,
 Avtor VARCHAR(255) NULL,
 KolichestvoStranic INT NULL,
 URLOblozhki VARCHAR(255) NULL,
 URLOpisaniya VARCHAR(255) NULL,
 Tegi VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Spiker (
 primaryKey UUID NOT NULL,
 Familiya VARCHAR(255) NOT NULL,
 Imya VARCHAR(255) NOT NULL,
 Otchestvo VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMNETLOCKDATA (
 LockKey VARCHAR(300) NOT NULL,
 UserName VARCHAR(300) NOT NULL,
 LockDate TIMESTAMP(3) NULL,
 PRIMARY KEY (LockKey));


CREATE TABLE STORMSETTINGS (
 primaryKey UUID NOT NULL,
 Module VARCHAR(1000) NULL,
 Name VARCHAR(255) NULL,
 Value TEXT NULL,
 "User" VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMAdvLimit (
 primaryKey UUID NOT NULL,
 "User" VARCHAR(255) NULL,
 Published BOOLEAN NULL,
 Module VARCHAR(255) NULL,
 Name VARCHAR(255) NULL,
 Value TEXT NULL,
 HotKeyData INT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERSETTING (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NOT NULL,
 DataObjectView VARCHAR(255) NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMWEBSEARCH (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NOT NULL,
 "Order" INT NOT NULL,
 PresentView VARCHAR(255) NOT NULL,
 DetailedView VARCHAR(255) NOT NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERDETAIL (
 primaryKey UUID NOT NULL,
 Caption VARCHAR(255) NOT NULL,
 DataObjectView VARCHAR(255) NOT NULL,
 ConnectMasterProp VARCHAR(255) NOT NULL,
 OwnerConnectProp VARCHAR(255) NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERLOOKUP (
 primaryKey UUID NOT NULL,
 DataObjectType VARCHAR(255) NOT NULL,
 Container VARCHAR(255) NULL,
 ContainerTag VARCHAR(255) NULL,
 FieldsToView VARCHAR(255) NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE UserSetting (
 primaryKey UUID NOT NULL,
 AppName VARCHAR(256) NULL,
 UserName VARCHAR(512) NULL,
 UserGuid UUID NULL,
 ModuleName VARCHAR(1024) NULL,
 ModuleGuid UUID NULL,
 SettName VARCHAR(256) NULL,
 SettGuid UUID NULL,
 SettLastAccessTime TIMESTAMP(3) NULL,
 StrVal VARCHAR(256) NULL,
 TxtVal TEXT NULL,
 IntVal INT NULL,
 BoolVal BOOLEAN NULL,
 GuidVal UUID NULL,
 DecimalVal DECIMAL(20,10) NULL,
 DateTimeVal TIMESTAMP(3) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE ApplicationLog (
 primaryKey UUID NOT NULL,
 Category VARCHAR(64) NULL,
 EventId INT NULL,
 Priority INT NULL,
 Severity VARCHAR(32) NULL,
 Title VARCHAR(256) NULL,
 Timestamp TIMESTAMP(3) NULL,
 MachineName VARCHAR(32) NULL,
 AppDomainName VARCHAR(512) NULL,
 ProcessId VARCHAR(256) NULL,
 ProcessName VARCHAR(512) NULL,
 ThreadName VARCHAR(512) NULL,
 Win32ThreadId VARCHAR(128) NULL,
 Message VARCHAR(2500) NULL,
 FormattedMessage TEXT NULL,
 PRIMARY KEY (primaryKey));



 ALTER TABLE Doklad ADD CONSTRAINT FKeb72d067c6b5800ed6c38ae1c177282d0974fe30 FOREIGN KEY (Spiker_m0) REFERENCES Spiker; 
CREATE INDEX Indexeb72d067c6b5800ed6c38ae1c177282d0974fe30 on Doklad (Spiker_m0); 

 ALTER TABLE Doklad ADD CONSTRAINT FKb02ab2cc0eed145af6ccbda0ad69d98d28fa1a29 FOREIGN KEY (Kniga_m0) REFERENCES Kniga; 
CREATE INDEX Indexb02ab2cc0eed145af6ccbda0ad69d98d28fa1a29 on Doklad (Kniga_m0); 

 ALTER TABLE Doklad ADD CONSTRAINT FK4d619bec21f224301eb50aea1c7854dd736000d4 FOREIGN KEY (VstrechaKluba_m0) REFERENCES VstrechaKluba; 
CREATE INDEX Index4d619bec21f224301eb50aea1c7854dd736000d4 on Doklad (VstrechaKluba_m0); 

 ALTER TABLE STORMWEBSEARCH ADD CONSTRAINT FKc4378e39870eb056aec84088683297a01d2a6200 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERDETAIL ADD CONSTRAINT FK921d16269835017e2a0d0e29ad6fb175454a70d0 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERLOOKUP ADD CONSTRAINT FKce38ef0db3f01a53acaa49fed8853fb941ad47ba FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

